name: Release Tauri App

on:
  push:
    tags:
      - "app-v*"
  workflow_dispatch:

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest"
            args: "--target aarch64-apple-darwin"
          - platform: "macos-latest"
            args: "--target x86_64-apple-darwin"
          - platform: "ubuntu-22.04"
            args: ""
          - platform: "windows-latest"
            args: ""
          - platform: "ubuntu-latest"
            args: "--apk --target aarch64"
            mobile: "android"

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          # node-version: lts/*
          # Fixed: https://github.com/nodejs/node/issues/62012 (EBADF fstat with Yarn in v24.15/v25.7+)
          node-version: 22

      - name: install Rust stable (desktop)
        if: matrix.mobile == ''
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: install Rust stable (android)
        if: matrix.mobile == 'android'
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android,armv7-linux-androideabi,i686-linux-android,x86_64-linux-android
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          workspaces: ./flying-android/src-tauri -> target

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04' || matrix.platform == 'ubuntu-24.04-arm'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: install frontend dependencies
        working-directory: ./flying-android
        run: |
          corepack enable
          yarn

      # ------------- Android -------------
      - name: Set up JDK
        if: matrix.mobile == 'android'
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Setup Android SDK
        if: matrix.mobile == 'android'
        uses: android-actions/setup-android@v3

      - name: Setup Android NDK
        if: matrix.mobile == 'android'
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r29
          link-to-sdk: true

      - name: setup Android signing
        if: matrix.mobile == 'android'
        run: |
          cd ./flying-android/src-tauri/gen/android
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" > keystore.properties
          echo "password=${{ secrets.ANDROID_KEY_PASSWORD }}" >> keystore.properties
          base64 -d <<< "${{ secrets.ANDROID_KEY_BASE64 }}" > $RUNNER_TEMP/keystore.jks
          echo "storeFile=$RUNNER_TEMP/keystore.jks" >> keystore.properties

      - uses: tauri-apps/tauri-action@850c373b94f35e16e4de61cbb9f6e4876af8c0b4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        with:
          projectPath: ./flying-android
          tagName: ${{ github.ref_name }}
          releaseName: "Flying App ${{ github.ref_name }}"
          releaseBody: "See the assets to download and install this version."
          releaseDraft: false
          prerelease: false
          args: ${{ matrix.args }}
          mobile: ${{ matrix.mobile }}
